
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const GET_PROF_DETAILS_REQUEST = 'GET_PROF_DETAILS_REQUEST';
const GET_PROF_DETAILS_SUCCESS = 'GET_PROF_DETAILS_SUCCESS';
const GET_PROF_DETAILS_FAILURE = 'GET_PROF_DETAILS_FAILURE';

const VEH_REQUEST = 'VEH_REQUEST';
const VEH_SUCCESS = 'VEH_SUCCESS';
const VEH_FAILURE = 'VEH_FAILURE';

const FIND_RIDE_REQUEST = 'FIND_RIDE_REQUEST';
const FIND_RIDE_SUCCESS = 'FIND_RIDE_SUCCESS';
const FIND_RIDE_FAILURE = 'FIND_RIDE_FAILURE';
const FIND_RIDE_CLEAR_PROPS='FIND_RIDE_CLEAR_PROPS';

const VEH_UPCOM_RIDE_REQUEST = ' VEH_UPCOM_RIDE_REQUEST';
const VEH_UPCOM_RIDE_SUCCESS = ' VEH_UPCOM_RIDE_SUCCESS';
const VEH_UPCOM_RIDE_FAILURE = ' VEH_UPCOM_RIDE_FAILURE';
const VEH_UPCOM_RIDE_CLEAR_PROPS='VEH_UPCOM_RIDE_CLEAR_PROPS';

const PLACES_REQUEST = ' PLACES_REQUEST';
const PLACES_SUCCESS = ' PLACES_SUCCESS';
const PLACES_FAILURE = ' PLACES_FAILURE';
const PLACES_CLEAR_PROPS='PLACES_CLEAR_PROPS';

const COM_REQ_RIDE_REQUEST = ' COM_REQ_RIDE_REQUEST';
const COM_REQ_RIDE_SUCCESS = ' COM_REQ_RIDE_SUCCESS';
const COM_REQ_RIDE_FAILURE = ' COM_REQ_RIDE_FAILURE';
const COM_REQ_RIDE_CLEAR_PROPS='COM_REQ_RIDE_CLEAR_PROPS';

const VEH_NOTIFICATION_REQUEST = ' VEH_NOTIFICATION_REQUEST';
const VEH_NOTIFICATION_SUCCESS = ' VEH_NOTIFICATION_SUCCESS';
const VEH_NOTIFICATION_FAILURE = ' VEH_NOTIFICATION_FAILURE';
const VEH_NOTIFICATION_CLEAR_PROPS='VEH_NOTIFICATION_CLEAR_PROPS';

const COM_NOTIFICATION_REQUEST = ' COM_NOTIFICATION_REQUEST';
const COM_NOTIFICATION_SUCCESS = ' COM_NOTIFICATION_SUCCESS';
const COM_NOTIFICATION_FAILURE = ' COM_NOTIFICATION_FAILURE';
const COM_NOTIFICATION_CLEAR_PROPS='COM_NOTIFICATION_CLEAR_PROPS';

const REQ_RIDE_REQUEST = ' REQ_RIDE_REQUEST';
const REQ_RIDE_SUCCESS = ' REQ_RIDE_SUCCESS';
const REQ_RIDE_FAILURE = ' REQ_RIDE_FAILURE';
const REQ_RIDE_CLEAR_PROPS='REQ_RIDE_CLEAR_PROPS';

const VEH_PAST_RIDE_REQUEST = ' VEH_PAST_RIDE_REQUEST';
const VEH_PAST_RIDE_SUCCESS = ' VEH_PAST_RIDE_SUCCESS';
const VEH_PAST_RIDE_FAILURE = ' VEH_PAST_RIDE_FAILURE';
const VEH_PAST_RIDE_CLEAR_PROPS='VEH_PAST_RIDE_CLEAR_PROPS';

const COM_UPCOME_RIDE_REQUEST = ' COM_UPCOME_RIDE_REQUEST';
const COM_UPCOME_RIDE_SUCCESS = ' COM_UPCOME_RIDE_SUCCESS';
const COM_UPCOME_RIDE_FAILURE = ' COM_UPCOME_RIDE_FAILURE';
const COM_UPCOME_RIDE_CLEAR_PROPS='COM_UPCOME_RIDE_CLEAR_PROPS';

const COM_PAST_RIDE_REQUEST = ' COM_PAST_RIDE_REQUEST';
const COM_PAST_RIDE_SUCCESS = ' COM_PAST_RIDE_SUCCESS';
const COM_PAST_RIDE_FAILURE = ' COM_PAST_RIDE_FAILURE';
const COM_PAST_RIDE_CLEAR_PROPS='COM_PAST_RIDE_CLEAR_PROPS';

const VERIFY_REQUEST = 'VERIFY_REQUEST';
const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
const VERIFY_FAILURE = 'VERIFY_FAILURE';


